cookie_secret: secure-key
xsrf_secret: another-secure-key
gae_remote_key: and-another-secure-key
gae_app_id: gitreview
gae_host: localhost:8080
gae_secure: off
gae_mail_sender: '"Git Review" <no-reply@espians.com>'
github_account: gitreview
repos:
  ampify:
    github: [tav, ampify]
    maintainer: tav
  naaga:
    github: [tav, naaga]
    maintainer: tav
